export const FETCH_BUILDING = "FETCH_BUILDING";
export const FETCH_RENT = "FETCH_RENT";
export const RELEASE_UNIT="RELEASE_UNIT";
export const FETCH_DISTRICTS="FETCH_DISTRICTS";
export const SET_CURRENT_DISTRICT="SET_CURRENT_DISTRICT";

export const FETCH_COMMS="FETCH_COMMS";
