export const FETCH_BUILDING = "FETCH_BUILDING";
export const FETCH_BUILDINGS = "FETCH_BUILDINGS";
export const ADD_BUILDINGS = "ADD_BUILDINGS";
export const FETCH_RENT = "FETCH_RENT";
export const RELEASE_UNIT="RELEASE_UNIT";
export const FETCH_DISTRICTS="FETCH_DISTRICTS";
export const SET_CURRENT_DISTRICT="SET_CURRENT_DISTRICT";

export const FETCH_COMMS="FETCH_COMMS";
export const SET_CURRENT_COMM="SET_CURRENT_COMM";

export const SET_AREA="SET_AREA";
export const SET_PRICE="SET_PRICE";

export const ADD_BUILDINGS="ADD_BUILDINGS";
